spring:
  grpc:
#    remote-servers:
#      - server: dome-2
#        host: 0.0.0.0
#        port: 6565
#      - server: dome-1
#        host: 0.0.0.0
#        port: 6566
    remote-servers:
      - server: dome-2
        host: 127.0.0.1
        port: 6565
      - server: dome-1
        host: 127.0.0.1
        port: 6566
server:
  port: 8080

